name: 'Code sign a DLL'
description: 'Sign a DLL with a code signing certificate.'
branding:
  icon: 'pen-tool'
  color: 'green'
inputs:
  certificate:
    description: 'The base64 encoded certificate.'
    required: true
  folder:
    description: 'The folder that contains the libraries to sign.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
