name: 'Code Sign'
description: 'Sign libraries with a code signing certificate.'
inputs:
  certificate:
    description: 'The base64 encoded certificate.'
    required: true
  folder:
    description: 'The folder that contains the libraries to sign.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'