on: push

jobs:
  run_action:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Copy library
        shell: cmd
        run: |
          mkdir files
          copy C:\Windows\System32\wmi.dll files
      - name: Run the action
        uses: ./
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          folder: 'files'