on: push

jobs:
  run_action:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run the action
        uses: ./
        with:
          certificate: '${{ secrets.CERTIFICATE }}'